# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ff36aa3755e614feb364bb14ec8a897b0be26517f5e7e45aeeb1f4cef127623757f1524afed48840d4ff2027cc93322130a6a4ce83bafc70d1cb4088476965

test:
  secret_key_base: cefdf762d8759a5f2a785dae2f7456208ec20d5815f6affa6fd234feb0fff28775a18ebca1787b3044e695309abad6371b491dc449cafe69d3bf717d4eb07533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
